# Generated by Django 4.2 on 2025-02-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuser',
            name='email',
            field=models.CharField(default='', max_length=68, unique=True),
        ),
    ]
