# Generated by Django 4.2 on 2025-02-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='minuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
