# Generated by Django 4.2 on 2025-02-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_minuser_is_staff_minuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='minuser',
            name='is_superuser',
        ),
    ]
