# Generated by Django 4.2 on 2025-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_minuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuser',
            name='email',
            field=models.CharField(default='abc', max_length=68, unique=True),
        ),
    ]
