# Generated by Django 4.2 on 2025-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_minuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuser',
            name='email',
            field=models.CharField(max_length=68, unique=True),
        ),
        migrations.AlterField(
            model_name='minuser',
            name='username',
            field=models.CharField(max_length=58, null=True),
        ),
    ]
