# Generated by Django 4.2 on 2025-02-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_minuser_email_alter_minuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuser',
            name='uid',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='minuser',
            name='email',
            field=models.CharField(max_length=65, unique=True),
        ),
        migrations.AlterField(
            model_name='minuser',
            name='password',
            field=models.CharField(max_length=257),
        ),
        migrations.AlterField(
            model_name='minuser',
            name='username',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
