# Generated by Django 4.2 on 2025-02-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_minuser_uid_alter_minuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuser',
            name='username',
            field=models.CharField(default='anonim', max_length=21, null=True),
        ),
    ]
