# Generated by Django 4.2 on 2025-02-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_minuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
