# Generated by Django 4.2 on 2025-02-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_minuser_groups_minuser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minuser',
            options={'verbose_name': 'MinUser', 'verbose_name_plural': 'MinUser'},
        ),
    ]
