# Generated by Django 4.2 on 2025-02-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_minuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuser',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
