# Generated by Django 4.2 on 2025-02-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_minuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuser',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
