# Generated by Django 4.2 on 2025-02-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_minuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuser',
            name='email',
            field=models.CharField(max_length=67, unique=True),
        ),
    ]
