# Generated by Django 4.2 on 2025-02-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_minuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuser',
            name='email',
            field=models.CharField(max_length=68, unique=True),
        ),
        migrations.AlterField(
            model_name='minuser',
            name='password',
            field=models.CharField(max_length=258),
        ),
        migrations.AlterField(
            model_name='minuser',
            name='username',
            field=models.CharField(default='', max_length=58),
        ),
    ]
