# Generated by Django 4.2 on 2025-02-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_minuser_email_alter_minuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuser',
            name='username',
            field=models.CharField(default=' ', max_length=58),
        ),
    ]
