# Generated by Django 4.2 on 2025-02-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_minuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuser',
            name='username',
            field=models.CharField(default='-', max_length=58),
        ),
    ]
