# Generated by Django 4.1.3 on 2025-02-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokens',
            name='is_activate',
        ),
    ]
