# Generated by Django 4.2 on 2025-02-10 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=100000)),
                ('message', models.CharField(max_length=5000)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
