# Generated by Django 4.2 on 2025-02-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Message'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='email_user',
        ),
        migrations.AddField(
            model_name='message',
            name='name_chat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='uid',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='message',
            name='id_chat',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
