# Generated by Django 4.2 on 2025-02-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='id_chat',
            field=models.IntegerField(default=0, max_length=100000),
        ),
        migrations.AlterField(
            model_name='chats',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='id_user',
            field=models.IntegerField(default=0, max_length=100000),
        ),
        migrations.AlterField(
            model_name='chats',
            name='message',
            field=models.IntegerField(default='', max_length=5000),
        ),
    ]
