# Generated by Django 4.2 on 2025-02-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_chats_id_chat_alter_chats_date_alter_chats_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='message',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
