# Generated by Django 4.2 on 2025-02-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_message_options_remove_message_email_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
