# Generated by Django 4.2 on 2025-02-10 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_chats_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 10)),
        ),
    ]
