# Generated by Django 4.2 on 2025-02-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_rename_message_message_content_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content_message',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='id_chat',
            field=models.CharField(default='', max_length=101),
        ),
        migrations.AlterField(
            model_name='message',
            name='name_chat',
            field=models.CharField(default='', max_length=101),
        ),
        migrations.AlterField(
            model_name='message',
            name='uid',
            field=models.CharField(default='', max_length=101),
        ),
    ]
