# Generated by Django 4.2 on 2025-02-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_chats_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
