# Generated by Django 4.2 on 2025-02-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_message_content_message_alter_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content_message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='id_chat',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='name_chat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='uid',
            field=models.CharField(default='', max_length=6),
        ),
    ]
